### ISSUE TITLE
COPYRIGHT VIOLATION README - Just making a point

### ISSUE THREAD

**Issue by greenreader9** [jaikt/vigil#2]
I don't think it's fair that you copied almost this entire thing from @mathab003's MOFHY-Lite. You really should give credit, it's an unwritten rule. You didn't write the code, so don't take credit for it. Yes, this belongs in the issue category, because I have a huge issue with what you have done. 

Additionally, you are violating copyright law. Please read the license of the respiratory you copied, and you will find that what you did is illegal.

**Comment by jaikt** [comment]
Ok so you want me to give credit right?
